# Generated by Django 3.2 on 2021-04-29 23:20

from django.db import migrations, models
import django.db.models.deletion
import projetos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Cadastro em Andamento'), (2, 'Aguardando Aprovação'), (3, 'Aprovado'), (4, 'Reprovado'), (5, 'Removido'), (6, 'Novo Status')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to=projetos.models.caminho_projeto)),
                ('tags', models.ManyToManyField(related_name='projetos', to='projetos.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('arquivo', models.FileField(upload_to=projetos.models.caminho_local)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='projetos.projeto')),
            ],
        ),
    ]
