# Generated by Django 3.2 on 2021-04-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20210429_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apelido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apelidos', to='projetos.projeto')),
            ],
        ),
    ]
