# Generated by Django 3.1 on 2020-08-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Cadastro em Andamento'), (2, 'Aguardando Aprovação'), (3, 'Aprovado'), (4, 'Reprovado'), (5, 'Removido')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tags',
            field=models.ManyToManyField(related_name='projetos', to='projetos.Tag'),
        ),
    ]
