# Generated by Django 3.1 on 2020-08-22 21:53

from django.db import migrations
from projetos.models import TagChoices


def criar_tags(apps, schema_editor):
    Tag = apps.get_model('projetos', 'Tag')
    for choice in TagChoices:
        Tag.objects.create(id=choice)


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20200822_1853'),
    ]

    operations = [
        migrations.RunPython(criar_tags)
    ]
